name: Rabbit Quality Gate [Linter & Test & SonarCloud]

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: '${{ secrets.GO_REPO_TOKEN }}'
          go_version_file: go.mod
          golangci_lint_version: 'v1.64.8'
          golangci_lint_flags: "--exclude-dirs-use-default --timeout 10m"
          reporter: github-pr-review
          level: error
      - name: Report suspicious constructs
        run: go vet ./...
