name: Rabbit Quality Gate [Linter & Test & SonarCloud]

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Config git with private repos
        env:
          GO_REPO_TOKEN: ${{ secrets.GO_REPO_TOKEN }}
        run: |
          git config --global url."https://${GO_REPO_TOKEN}:x-oauth-basic@github.com/".insteadOf https://github.com/
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: go.mod
          reporter: github-pr-review
          golangci_lint_flags: "--exclude-dirs-use-default --timeout 10m"
      - name: Report suspicious constructs
        run: go vet ./...